### PR TITLE
Generate test files/dirs in app tests

### LINKED ISSUE #149: Properly mock file and dirs in app tests to not read from the filesystem
### Description

Shown in [this build failure](https://travis-ci.org/github/commander-cli/commander/builds/737584463). The test in apps is currently targeting example suites in `examples/`. This should be properly mocked.

### PR DESCRIPTION
**Pull request by dylanhitt**
Fixes #149 

## Checklist

 - [x] Added unit / integration tests for windows, macOS and Linux? 
 - [ ] Added a changelog entry in [CHANGELOG.md](https://github.com/commander-cli/commander/blob/master/CHANGELOG.md)?
 - [ ] Updated the documentation ([README.md](https://github.com/commander-cli/commander/blob/master/README.md), [docs](https://github.com/commander-cli/commander/blob/master/docs))?
 - [x] Does your change work on `Linux`, `Windows` and `macOS`?

### CODE REVIEW

**Comment by SimonBaeumer** [comment]
Hey @dylanhitt,
I am not sure if you read my comment in the other pull request.
You should make use of `testdata` inside the same directory, see my comment: https://github.com/commander-cli/commander/pull/147#discussion_r510670081
Than it is not necessary to create a temp directory / file.

Have a nice weekend! :)

**Comment by dylanhitt** [comment]
Oh, I was unsure. I was following the pattern I saw in `test_command_linux_test.go`. Should we just migrate everything to `tesdata`?

**Comment by SimonBaeumer** [comment]
> Oh, I was unsure. I was following the pattern I saw in `test_command_linux_test.go`. Should we just migrate everything to `tesdata`?

Yes, was not my best idea :D If you would like to you can refactor it too :)

**Comment by dylanhitt** [comment]
I'm gonna close this and re implement with `testData`

**Pull request closed without merging**
