### PR TITLE
Move commander from SimonBaeumer/commander to commander-cli/commander

### LINKED ISSUE #134: Moving commander to an orginisation
As the activity in this project grows I would like to suggest to move commander into its own organisation.

Benefits would be:

 - Code ownership is not mine alone
 - More people are encouraged to join the project
 - Hopefully better permission configurations for new contributors
 - Creating more packages together 

Downside:

 - Repo link would change (redirects are managed by github)

For me it is important that the project is fun to work with and helps us to learn new things - and as a side effect doing something useful for the community.

Is there interest in this step?

### PR DESCRIPTION
**Pull request by SimonBaeumer**
Fixes #134 

## Checklist

 - [x] Added unit / integration tests for windows, macOS and Linux? 
 - [x] Added a changelog entry in [CHANGELOG.md](../CHANGELOG.md)?
 - [x] Updated the documentation ([README.md](../README.md), [docs](../docs))?
 - [x] Does your change work on `Linux`, `Windows` and `macOS`?
 - [x] codeclimate integration
 - [x] dependencies
 - [x] travis integration
 - [x] deployment

### CODE REVIEW

**Comment by SimonBaeumer** [comment]
Release deployment needs to be fixed, currently it fails because the oauth token is not actual anymore.
Further `SimonBaeumer/cmd` should be replaced by `commander-cli/cmd`

**Comment by dylanhitt** [comment]
Let me know when this is done. I'll look through the codebase and see if I can find anything.

**Comment by SimonBaeumer** [comment]
> Let me know when this is done. I'll look through the codebase and see if I can find anything.

The migration is finished. I would like to merge #126 before this. The build will break the master branch temporary but imho it shouldn't be a big problem because your current builds work.
After merging of #126 this PR can get merged and can move on with other PRs.

**Comment by SimonBaeumer** [comment]
@dylanhitt finished, awaiting your review

**Comment by SimonBaeumer** [comment]
> I think you got everything.
> 
> The one thing I did notice though is that in the PR template the links to markup files do not work. I believes it's because github doesn't support relative linking in PRs??? I can't really find anything saying it is or isn't .
> 
> Thank you for doing the migration by the way. These things are never fun to do.

Good catch, thanks! Fixed the links and tried it - as you said, github does not support relative links in PRs.

**Pull request merged**
