### PR TITLE
Lint, gofmt

### PR DESCRIPTION
**Pull request by taigrr**
Updates code to remove deprecation notices and update dependencies accordingly. 
Runs `gofmt`, `golint`, etc. to apply DeMorgan's law, and use go code simplifier. 
Removes dependency on deprecated `ioutil` package.

## Checklist

 - [ ] Added unit / integration tests for windows, macOS and Linux? 
 - [ ] Added a changelog entry in [CHANGELOG.md](https://github.com/commander-cli/commander/blob/master/CHANGELOG.md)?
 - [ ] Updated the documentation ([README.md](https://github.com/commander-cli/commander/blob/master/README.md), [docs](https://github.com/commander-cli/commander/blob/master/docs))?
 - [X] Does your change work on `Linux`, `Windows` and `macOS`?

### CODE REVIEW

**Comment by taigrr** [comment]
Due to vendoring, this looks like a >250K line diff, but I've kept my commits atomic. Hopefully it's not too painful to review.

**Comment by dylanhitt** [comment]
Looking at the tests it doesn't look to be building.

**Comment by taigrr** [comment]
Thanks, I couldn't see the failures before but they're caused by docker using strings.Cut, which wasn't introduced to stdlib until go 1.18. commander + circleci was set to 1.17. Debian stable supports 1.19, so I've updated the go version numbers to 1.19.

**Comment by dylanhitt** [comment]
Seems they changed their image names: https://circleci.com/developer/images/image/cimg/go 😄

**Comment by taigrr** [comment]
I can locally `docker pull` cimg/go:1.19.0, so I'm not sure what's happening on circleci's end.

**Comment by taigrr** [comment]
Looks like first, curl was refusing to run, and now the test-reporter is refusing to run. Is there a chance you might be able to look into the test-reporter failure?

**Comment by taigrr** [comment]
the  `/bin/sh` failure is what's got me scratching my head.

```Starting tests
+ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --network commander_test --name commander-integration-go-test --env CC_TEST_REPORTER_ID=**************************************************************** commander-int-test make integration-linux
INFO: Starting build build
go build cmd/commander/*
make: /bin/sh: Operation not permitted
make: *** [Makefile:22: build] Error 127
make: *** [Makefile:85: integration-linux-dockerized] Error 2

Exited with code exit status 2
CircleCI received exit code 2```

**Comment by taigrr** [comment]
With that reversion, my PR and you master 1.21 bump should match.

**Comment by dylanhitt** [comment]
Also this...

```
Digest: sha256:b113af1e8b06f06a18ad41a6b331646dff587d7a4cf740f4852d16c49ed8ad73
Status: Downloaded newer image for golang:1.21
root@1a751dc82d21:/go# curl
curl: try 'curl --help' or 'curl --manual' for more information
root@1a751dc82d21:/go#
```

curl is definitely in there... In the past I have problem swith circle and it's transient errors...

**Comment by dylanhitt** [comment]
Alright so something about make and latest debian, when executing in circle ci, only when executing from a docker run, on a thursday in November, does it not work 🥲 

But yeah I set the test image back to debian bullseye. I don't really feel like opening the issues for all the places cause we're probably not gonna get anywhere. Hopefully some big corporation hits a wall with this 🤷. Probably will just move to github actions when the time comes.

**Comment by taigrr** [comment]
@dylanhitt it's now friday UTC and the tests have passed. 🤣

**Comment by taigrr** [comment]
Hey, don't mean to double tag but the github outage lost all my pr notifications so in case yours are gone too, I'm bumping this. Feel free to ignore if you're busy.

**Review by dylanhitt — APPROVED** [review]
👍

**Comment by dylanhitt** [comment]
@taigrr can you squash this into one commit.

Thank you

**Comment by taigrr** [comment]
Whoops, my indexes were off by one. Is this ok?

**Comment by taigrr** [comment]
Should be able to do a squash from the github UI now as well

**Comment by taigrr** [comment]
Looks like not all the integration tests run in the PR that run on master

**Comment by dylanhitt** [comment]
Yeah, the windows test burn through circle ci minutes. Feel free to fix them or I'll do it later.

**Comment by taigrr** [comment]
I think just need to update the windows version tag from v2.1.0 to v5.0.0, but I can't trigger the CI to test without a merge so it's best for you to do it

**Pull request merged**
