### PR TITLE
update docs to go get v2

### LINKED ISSUE #166: documented install command fails with go 1.16
### Prerequisites

* [x] Can you reproduce the problem?
* [x] Are you running the latest version?
* [ ] Did you perform a cursory search?

### Description

When attempting to install `commander` using `go get` *outside* of the `commander` project directory, it fails.
```bash
$ cd && go clean -cache -modcache && go get github.com/commander-cli/commander/cmd/commander
go get: github.com/commander-cli/commander@none updating to
        github.com/commander-cli/commander@v1.3.0: parsing go.mod:
        module declares its path as: github.com/SimonBaeumer/commander
                but was required as: github.com/commander-cli/commander
```
Running the `go get` command within the `commander` project directory completes successfully:
```bash
$ git clone https://github.com/commander-cli/commander && cd commander &&  go clean -cache -modcache && go get github.com/commander-cli/commander/cmd/commander
```

### Steps to Reproduce

1. Install `go` 1.16.
2. Attempt to install `commander` outside project directory:
```bash
cd && go clean -cache -modcache -i -r && go get github.com/commander-cli/commander/cmd/commander
```
**Expected behavior:**
A working `commander` binary installed in `GOBIN`.

**Actual behavior:**
`go get` fails.

### Specifications

 - Version: n/a but needs `go` `1.16` to reproduce.
 - Platform: tested on MacOS and Linux
 - Subsystem: 
 
You can get the version information from executing `commander --version`.

### PR DESCRIPTION
**Pull request by dylanhitt**
Fixes #166 

## Checklist

 - [ ] Added unit / integration tests for windows, macOS and Linux? 
 - [ ] Added a changelog entry in [CHANGELOG.md](https://github.com/commander-cli/commander/blob/master/CHANGELOG.md)?
 - [ ] Updated the documentation ([README.md](https://github.com/commander-cli/commander/blob/master/README.md), [docs](https://github.com/commander-cli/commander/blob/master/docs))?
 - [ ] Does your change work on `Linux`, `Windows` and `macOS`?

### CODE REVIEW

**Comment by dylanhitt** [comment]
@SimonBaeumer 

Pointed out in #166. We need a release and the docs updated to truly close that issue.

**Review by SimonBaeumer — COMMENTED** [review]
Thanks @dylanhitt!

**Review by SimonBaeumer — APPROVED** [review]

**Comment by dylanhitt** [comment]
@SimonBaeumer I believe we still need a release for this to be fixed.

This works

```bash
$ docker run -it golang:1.16 bash
root@f9ebdbe11643:/go# go get github.com/commander-cli/commander/v2/cmd/commander@master
go: downloading github.com/commander-cli/commander/v2 v2.4.1-0.20210628071648-b0fc0049dbf0
go: downloading github.com/commander-cli/commander v1.3.1-0.20210325101804-b02796834fae
go: downloading github.com/commander-cli/cmd v1.3.0
go: downloading github.com/urfave/cli v1.22.5
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/logrusorgru/aurora v2.0.3+incompatible
go: downloading github.com/docker/docker v1.13.1
go: downloading golang.org/x/crypto v0.0.0-20210322153248-0c34fe9e7dc2
go: downloading github.com/antchfx/xmlquery v1.3.5
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/tidwall/gjson v1.7.1
go: downloading github.com/stretchr/testify v1.7.0
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading github.com/antchfx/xpath v1.1.10
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading golang.org/x/net v0.0.0-20210226172049-e18ecbb05110
go: downloading github.com/tidwall/match v1.0.3
go: downloading github.com/tidwall/pretty v1.1.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading golang.org/x/sys v0.0.0-20201119102817-f84b799fce68
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/Microsoft/go-winio v0.4.16
go: downloading github.com/opencontainers/go-digest v1.0.0
```

This does not:

```bash
$ docker run -it golang:1.16 bash
root@76ad7770acec:/go# go get github.com/commander-cli/commander/v2/cmd/commander
go: downloading github.com/commander-cli/commander v1.3.0
go get: module github.com/commander-cli/commander@upgrade found (v1.3.0), but does not contain package github.com/commander-cli/commander/v2/cmd/commander
```

**Comment by dylanhitt** [comment]
I was unaware I could publish a release doing so now.

**Comment by dylanhitt** [comment]
That doesn't seem to fix the issue either 😞..

I think this will require a bit more research. I removed the tag/release I just published.

**Comment by dylanhitt** [comment]
I'm actually unsure how the release workflow works. As I've been unable to do it properly. I assumed you could just create a release. 

Either that or the jump for go `1.13` > `1.16` is breaking the CI.

**Pull request merged**
