### PR TITLE
Preserve execution order alphabetically by test title

### PR DESCRIPTION
**Pull request by SimonBaeumer**
Fixes #

## Checklist

 - [x] Added unit / integration tests for windows, macOS and Linux? 
 - [x] Added a changelog entry in [CHANGELOG.md](https://github.com/commander-cli/commander/blob/master/CHANGELOG.md)?
 - [x] Updated the documentation ([README.md](https://github.com/commander-cli/commander/blob/master/README.md), [docs](https://github.com/commander-cli/commander/blob/master/docs))?
 - [x] Does your change work on `Linux`, `Windows` and `macOS`?

### CODE REVIEW

**Comment by SimonBaeumer** [comment]
> I know it's not ready for review, but I found sometime. Is the plan to make the alphabetical ordering the default order or flag enabled?

The idea is to enable it by default because currently there is no order guranteed.

**Comment by SimonBaeumer** [comment]
@dylanhitt review? :+1:

**Comment by dylanhitt** [comment]
Sure, I'll look at it Sunday

**Comment by dylanhitt** [comment]
Reviewing Monday, current get to my computer today. Sorry about that.

**Comment by SimonBaeumer** [comment]
> Reviewing Monday, current get to my computer today. Sorry about that.

No problem, do it when you have time :+1:

**Comment by dylanhitt** [comment]
The only thing I really have to add is where do we mention "Commander test will execute tests in alphabetical order by default". I was thinking it should go in the commander `test` cli help text, and maybe a little bit of text under [executing](https://github.com/commander-cli/commander#executing). 

Hmm maybe a little example showing sequential execution. Something like you mentioned in #128.
```yaml
001 - it should print hello world:
  order: 1
  command: echo hello world
  stdout: hello world
  exit-code: 0

003 - it should validate exit code:
  order: 2
  command: exit 1
  exit-code: 1

002 - another test:
  order: 2
  command: exit 1
  exit-code: 1
```
Maybe a full suite example in `examples/` could go a long way. Your thoughts?

**Comment by SimonBaeumer** [comment]
> The only thing I really have to add is where do we mention "Commander test will execute tests in alphabetical order by default". I was thinking it should go in the commander `test` cli help text, and maybe a little bit of text under [executing](https://github.com/commander-cli/commander#executing).
> 
> Hmm maybe a little example showing sequential execution. Something like you mentioned in #128.
> 
> ```yaml
> 001 - it should print hello world:
>   order: 1
>   command: echo hello world
>   stdout: hello world
>   exit-code: 0
> 
> 003 - it should validate exit code:
>   order: 2
>   command: exit 1
>   exit-code: 1
> 
> 002 - another test:
>   order: 2
>   command: exit 1
>   exit-code: 1
> ```
> 
> Maybe a full suite example in `examples/` could go a long way. Your thoughts?

Good idea! I will add it to the help and extend the examples. 
Anyway I have extending the help command on my list as well.

**Pull request merged**
