### PR TITLE
Trim whitespace from file contents

### PR DESCRIPTION
**Pull request by glesica**
I noticed that the `file` matcher I added last year doesn't trim whitespace, whereas the executors do trim whitespace from the content they capture from stdout and stderr. This causes annoyance if you edit the "gold" file with an editor like Vim that automatically appends a newline. I also changed it to convert `\r\n` to `\n` to match the executors.

## Checklist

 - [x] Added unit / integration tests for windows, macOS and Linux? 
 - [x] Added a changelog entry in [CHANGELOG.md](https://github.com/commander-cli/commander/blob/master/CHANGELOG.md)?
 - [ ] Updated the documentation ([README.md](https://github.com/commander-cli/commander/blob/master/README.md), [docs](https://github.com/commander-cli/commander/blob/master/docs))?
 - [x] Does your change work on `Linux`, `Windows` and `macOS`?

### CODE REVIEW

**Comment by glesica** [comment]
@dylanhitt @SimonBaeumer ping :-)

**Review by dylanhitt — APPROVED** [review]
Sorry I seemed to miss this juggling some things. 

Nice - super informative with the `\r\n`

**Comment by dylanhitt** [comment]
@glesica would you mind force pushing your last commit. I just setup circleci to build forked PRs.

**Comment by glesica** [comment]
Not sure what's failing, exactly...

**Comment by dylanhitt** [comment]
So code coverage is failing to do forks not being allowed  to run env variables which is fine. 

The integration is failing because of the linecount not matching. You added a integration test so [`commander_unix.yaml`](https://github.com/commander-cli/commander/blob/master/commander_unix.yaml#L19) the test `it should execute tests` needs to be iterated by 1 😄

**Comment by glesica** [comment]
Oh that's right! I'd forgotten about those! Done!

**Pull request merged**
